version: '3.1'
services:
  db:
    image: mysql:8.0
    container_name: foodie
    environment:
      MYSQL_ROOT_PASSWORD: Welcome123456
      MYSQL_DATABASE: foodie
      MYSQL_USER: root
      MYSQL_PASSWORD: Welcome123456
    ports:
     - "3306:3306"
    volumes:
     - db_data:/var/lib/mysql

volumes:
  db_data: