version: '3.1'
services:
  db:
    image: mysql:8.0
    container_name: foodie
    environment:
      MYSQL_ROOT_PASSWORD: Welcome123456
      MYSQL_DATABASE: foodie
    ports:
     - "3306:3306"
    volumes:
     - ./mysql:/var/lib/mysql
     - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: