version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: foodie
    environment:
      MYSQL_ROOT_PASSWORD: foodie
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql